[build]
    base = "my_portfolio"
    publish = "My_Portfolio/dist/my_portfolio"
    command = "ng build --configuration production"

[build.environment]
    NODE_VERSION = "18"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200